name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - uses: psf/black@stable
        with:
          options: "--check --verbose"


  flake8:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: flake8
        env:
          GITHUB_TOKEN: $${{ secrets.GITHUB_TOKEN }}
